### PR TITLE
Introducing WheelChooser.number() ✅

### PR DESCRIPTION
**Pull request by moazelsawaf**
Hello Dear 👋🏻

First of all. thank you so much for the package and for helping the community get better and stronger 🙏🏻💙

Secondly, in this PR, you will find 2 new updates, which are the following:

1. [Added WheelChooser.number()](https://github.com/mafanwei/WheelChooser/commit/f57d931441110126755cef1ebc0bf51bd9810b44), to accept and deal with values of type `num` instead of only integers ✅
2. [Added physics property](https://github.com/mafanwei/WheelChooser/commit/d72f9a4fd30bbc6e74c02b11bb9b9a5e1d6b481d), to set the preferred `ScrollPhysics` 💙

I hope you like the updates ... 💙

Thanks, 🙏🏻
Moaz El-sawaf

### CODE REVIEW

**Comment by moazelsawaf** [comment]
@mafanwei 
Any Updates?

**Comment by mafanwei** [comment]
Can you solve conflicts?

**Comment by moazelsawaf** [comment]
Done ✅

**Comment by mafanwei** [comment]
Thank you

**Comment by moazelsawaf** [comment]
You're welcome 🙏🏻❤️

**Pull request merged**
